export interface AircraftInfo {
  name: string;
  flag: string;
  role: string;
  firstFlight: string;
  manufacturer: string;
  funFact: string;
}

const aircraftDatabase: Record<string, AircraftInfo> = {
  A10: {
    name: "Fairchild Republic A-10 Thunderbolt II",
    flag: "🇺🇸",
    role: "Close Air Support",
    firstFlight: "1972",
    manufacturer: "Fairchild Republic",
    funFact: "Built around a 30mm GAU-8 Avenger rotary cannon that can destroy tanks.",
  },
  A400M: {
    name: "Airbus A400M Atlas",
    flag: "🇪🇺",
    role: "Military Transport",
    firstFlight: "2009",
    manufacturer: "Airbus Defence and Space",
    funFact: "Powered by the world's most powerful turboprop engines, the TP400.",
  },
  AG600: {
    name: "AVIC AG600 Kunlong",
    flag: "🇨🇳",
    role: "Amphibious Firefighting / SAR",
    firstFlight: "2017",
    manufacturer: "AVIC",
    funFact: "Largest amphibious aircraft in the world; can scoop 12 tons of water in 20 seconds.",
  },
  AH64: {
    name: "Boeing AH-64 Apache",
    flag: "🇺🇸",
    role: "Attack Helicopter",
    firstFlight: "1975",
    manufacturer: "Boeing",
    funFact: "Primary attack helicopter of the US Army; used in every major US conflict since the Gulf War.",
  },
  AKINCI: {
    name: "Bayraktar Akıncı",
    flag: "🇹🇷",
    role: "High-Altitude Long-Endurance UCAV",
    firstFlight: "2019",
    manufacturer: "Baykar",
    funFact: "Turkey's heaviest armed drone; can carry cruise missiles and operate at 40,000 ft.",
  },
  AKSUNGUR: {
    name: "Bayraktar AKSUNGUR",
    flag: "🇹🇷",
    role: "MALE UAV",
    firstFlight: "2019",
    manufacturer: "Baykar",
    funFact: "Larger variant of the TB2, capable of carrying heavier payloads and more advanced sensors.",
  },
  AV8B: {
    name: "McDonnell Douglas AV-8B Harrier II",
    flag: "🇺🇸",
    role: "V/STOL Ground Attack",
    firstFlight: "1981",
    manufacturer: "McDonnell Douglas / BAE Systems",
    funFact: "Operates from amphibious assault ships; uses thrust vectoring for vertical landing.",
  },
  An124: {
    name: "Antonov An-124 Ruslan",
    flag: "🇺🇦",
    role: "Strategic Airlifter",
    firstFlight: "1982",
    manufacturer: "Antonov",
    funFact: "One of the world's largest cargo aircraft; can carry 150 tons of payload.",
  },
  An22: {
    name: "Antonov An-22 Antei",
    flag: "🇺🇦",
    role: "Heavy Transport",
    firstFlight: "1965",
    manufacturer: "Antonov",
    funFact: "Largest turboprop aircraft ever built; powered by four contra-rotating propellers.",
  },
  An225: {
    name: "Antonov An-225 Mriya",
    flag: "🇺🇦",
    role: "Ultra-Heavy Cargo Transport",
    firstFlight: "1988",
    manufacturer: "Antonov",
    funFact: "World's heaviest aircraft ever built; destroyed in 2022, but a second airframe exists.",
  },
  An72: {
    name: "Antonov An-72",
    flag: "🇺🇦",
    role: "STOL Transport",
    firstFlight: "1977",
    manufacturer: "Antonov",
    funFact: "Uses the Coandă effect for short takeoff and landing; exhaust blows over the wings.",
  },
  Anka3: {
    name: "TAI Anka-3",
    flag: "🇹🇷",
    role: "Stealth UCAV",
    firstFlight: "2023",
    manufacturer: "Turkish Aerospace Industries",
    funFact: "Turkey's first stealth flying-wing drone; designed for deep strike missions.",
  },
  B1: {
    name: "Rockwell B-1 Lancer",
    flag: "🇺🇸",
    role: "Strategic Bomber",
    firstFlight: "1974",
    manufacturer: "Rockwell International",
    funFact: "Can carry the largest payload of both guided and unguided weapons in the USAF inventory.",
  },
  B2: {
    name: "Northrop Grumman B-2 Spirit",
    flag: "🇺🇸",
    role: "Stealth Strategic Bomber",
    firstFlight: "1989",
    manufacturer: "Northrop Grumman",
    funFact: "Each aircraft costs approximately $2.1 billion; only 21 were built.",
  },
  B21: {
    name: "Northrop Grumman B-21 Raider",
    flag: "🇺🇸",
    role: "Stealth Strategic Bomber",
    firstFlight: "2023",
    manufacturer: "Northrop Grumman",
    funFact: "Next‑generation stealth bomber; designed to replace the B-1 and B-2.",
  },
  B52: {
    name: "Boeing B-52 Stratofortress",
    flag: "🇺🇸",
    role: "Strategic Bomber",
    firstFlight: "1952",
    manufacturer: "Boeing",
    funFact: "Expected to serve into the 2050s – nearly 100 years of service.",
  },
  Be200: {
    name: "Beriev Be-200 Altair",
    flag: "🇷🇺",
    role: "Amphibious Firefighting / SAR",
    firstFlight: "1998",
    manufacturer: "Beriev",
    funFact: "Only modern jet-powered amphibious aircraft in production.",
  },
  C130: {
    name: "Lockheed C-130 Hercules",
    flag: "🇺🇸",
    role: "Military Transport",
    firstFlight: "1954",
    manufacturer: "Lockheed Martin",
    funFact: "Over 2,500 built across 70+ years; one of the longest continuously produced military aircraft.",
  },
  C17: {
    name: "Boeing C-17 Globemaster III",
    flag: "🇺🇸",
    role: "Strategic / Tactical Airlifter",
    firstFlight: "1991",
    manufacturer: "Boeing",
    funFact: "Can land on short, austere runways as short as 3,500 ft while carrying heavy payloads.",
  },
  C2: {
    name: "Northrop Grumman C-2 Greyhound",
    flag: "🇺🇸",
    role: "Carrier Onboard Delivery",
    firstFlight: "1964",
    manufacturer: "Northrop Grumman",
    funFact: "Primary COD aircraft for the US Navy; replaced by the CMV-22 Osprey.",
  },
  C390: {
    name: "Embraer C-390 Millennium",
    flag: "🇧🇷",
    role: "Medium Transport",
    firstFlight: "2015",
    manufacturer: "Embraer",
    funFact: "Can be refueled in flight and also serve as a tanker with buddy pods.",
  },
  C5: {
    name: "Lockheed C-5 Galaxy",
    flag: "🇺🇸",
    role: "Strategic Airlifter",
    firstFlight: "1968",
    manufacturer: "Lockheed",
    funFact: "One of the largest military aircraft; can carry two M1 Abrams tanks.",
  },
  CH47: {
    name: "Boeing CH-47 Chinook",
    flag: "🇺🇸",
    role: "Heavy-Lift Helicopter",
    firstFlight: "1961",
    manufacturer: "Boeing Vertol",
    funFact: "Tandem-rotor design can carry 33 troops or 12 tons of cargo.",
  },
  CL415: {
    name: "Canadair CL-415",
    flag: "🇨🇦",
    role: "Amphibious Firefighter",
    firstFlight: "1993",
    manufacturer: "Canadair",
    funFact: "Designed specifically for water‑bombing; can scoop 6,100 litres in 12 seconds.",
  },
  E2: {
    name: "Northrop Grumman E-2 Hawkeye",
    flag: "🇺🇸",
    role: "Airborne Early Warning",
    firstFlight: "1960",
    manufacturer: "Northrop Grumman",
    funFact: "Eyes of the fleet — its radar dish rotates at 6 RPM and tracks 2,000+ targets.",
  },
  E7: {
    name: "Boeing E-7 Wedgetail",
    flag: "🇺🇸",
    role: "AEW&C",
    firstFlight: "2004",
    manufacturer: "Boeing",
    funFact: "Based on the 737-700; uses a fixed MESA radar instead of a rotating dome.",
  },
  EF2000: {
    name: "Eurofighter Typhoon",
    flag: "🇪🇺",
    role: "Multirole Fighter",
    firstFlight: "1994",
    manufacturer: "Airbus / BAE Systems / Leonardo",
    funFact: "Built by a consortium of four European nations: UK, Germany, Italy, and Spain.",
  },
  F117: {
    name: "Lockheed F-117 Nighthawk",
    flag: "🇺🇸",
    role: "Stealth Attack",
    firstFlight: "1981",
    manufacturer: "Lockheed",
    funFact: "First operational stealth aircraft; retired in 2008 but some remain flying.",
  },
  F14: {
    name: "Grumman F-14 Tomcat",
    flag: "🇺🇸",
    role: "Air Superiority / Fleet Defense",
    firstFlight: "1970",
    manufacturer: "Grumman",
    funFact: "Starred in Top Gun (1986); its variable‑sweep wings adjust from 20° to 68°.",
  },
  F15: {
    name: "McDonnell Douglas F-15 Eagle",
    flag: "🇺🇸",
    role: "Air Superiority Fighter",
    firstFlight: "1972",
    manufacturer: "McDonnell Douglas",
    funFact: "Undefeated in aerial combat with over 100 confirmed kills and zero losses.",
  },
  F16: {
    name: "General Dynamics F-16 Fighting Falcon",
    flag: "🇺🇸",
    role: "Multirole Fighter",
    firstFlight: "1974",
    manufacturer: "General Dynamics (now Lockheed Martin)",
    funFact: "Over 4,600 built, used by 25+ countries.",
  },
  F18: {
    name: "McDonnell Douglas F/A-18 Hornet",
    flag: "🇺🇸",
    role: "Multirole Fighter",
    firstFlight: "1978",
    manufacturer: "McDonnell Douglas",
    funFact: "Flown by the Blue Angels demonstration team; over 1,480 produced.",
  },
  F22: {
    name: "Lockheed Martin F-22 Raptor",
    flag: "🇺🇸",
    role: "Stealth Air Superiority",
    firstFlight: "1997",
    manufacturer: "Lockheed Martin",
    funFact: "First 5th‑generation fighter; production stopped at 187 aircraft due to cost.",
  },
  F35: {
    name: "Lockheed Martin F-35 Lightning II",
    flag: "🇺🇸",
    role: "Stealth Multirole Fighter",
    firstFlight: "2006",
    manufacturer: "Lockheed Martin",
    funFact: "Most expensive weapons program in history at $1.7 trillion.",
  },
  F4: {
    name: "McDonnell Douglas F-4 Phantom II",
    flag: "🇺🇸",
    role: "Interceptor / Fighter‑Bomber",
    firstFlight: "1958",
    manufacturer: "McDonnell Douglas",
    funFact: "Served with the armed forces of 11 nations and was the primary fighter during the Vietnam War.",
  },
  H6: {
    name: "Xian H-6",
    flag: "🇨🇳",
    role: "Strategic Bomber",
    firstFlight: "1959",
    manufacturer: "Xian Aircraft",
    funFact: "Chinese license‑built version of the Soviet Tu-16; still in service after 60 years.",
  },
  HURJET: {
    name: "TAI Hürjet",
    flag: "🇹🇷",
    role: "Advanced Jet Trainer / Light Combat",
    firstFlight: "2023",
    manufacturer: "Turkish Aerospace Industries",
    funFact: "Designed to replace the aging T-38 Talon in Turkish service.",
  },
  HURKUS: {
    name: "TAI Hürkuş",
    flag: "🇹🇷",
    role: "Trainer / Light Attack",
    firstFlight: "2013",
    manufacturer: "Turkish Aerospace Industries",
    funFact: "Turkey's first indigenous basic trainer aircraft.",
  },
  J10: {
    name: "Chengdu J-10 Vigorous Dragon",
    flag: "🇨🇳",
    role: "Multirole Fighter",
    firstFlight: "1998",
    manufacturer: "Chengdu Aerospace",
    funFact: "China's first domestically developed single-engine delta-canard fighter.",
  },
  J20: {
    name: "Chengdu J-20 Mighty Dragon",
    flag: "🇨🇳",
    role: "Stealth Air Superiority Fighter",
    firstFlight: "2011",
    manufacturer: "Chengdu Aerospace",
    funFact: "China's first 5th‑generation stealth fighter, rivaling the F-22 Raptor.",
  },
  JAS39: {
    name: "Saab JAS 39 Gripen",
    flag: "🇸🇪",
    role: "Multirole Fighter",
    firstFlight: "1988",
    manufacturer: "Saab",
    funFact: "Can operate from roads and requires only one ground crew of five to rearm and refuel.",
  },
  JF17: {
    name: "PAC / CAC JF-17 Thunder",
    flag: "🇵🇰",
    role: "Multirole Light Fighter",
    firstFlight: "2003",
    manufacturer: "Pakistan Aeronautical Complex / Chengdu",
    funFact: "Joint Pakistan‑China project; backbone of Pakistan Air Force.",
  },
  JH7: {
    name: "Xian JH-7 Flying Leopard",
    flag: "🇨🇳",
    role: "Strike Fighter",
    firstFlight: "1988",
    manufacturer: "Xian Aircraft",
    funFact: "China's first indigenous supersonic fighter‑bomber; still in service.",
  },
  KAAN: {
    name: "TAI KAAN (TF‑X)",
    flag: "🇹🇷",
    role: "5th‑Generation Stealth Fighter",
    firstFlight: "2024",
    manufacturer: "Turkish Aerospace Industries",
    funFact: "Turkey's first indigenous stealth fighter; aims to rival the F-35.",
  },
  KC135: {
    name: "Boeing KC-135 Stratotanker",
    flag: "🇺🇸",
    role: "Aerial Refueling Tanker",
    firstFlight: "1956",
    manufacturer: "Boeing",
    funFact: "Has refueled aircraft in every major US conflict since the Vietnam War.",
  },
  KF21: {
    name: "KAI KF-21 Boramae",
    flag: "🇰🇷",
    role: "Multirole Fighter",
    firstFlight: "2022",
    manufacturer: "Korea Aerospace Industries",
    funFact: "South Korea's first indigenous supersonic fighter; designed to be a 4.5‑gen aircraft.",
  },
  KIZILELMA: {
    name: "Bayraktar Kızılelma",
    flag: "🇹🇷",
    role: "Unmanned Fighter Aircraft",
    firstFlight: "2022",
    manufacturer: "Baykar",
    funFact: "Named after a legendary Turkish mythological goal; designed to operate from TCG Anadolu.",
  },
  KJ600: {
    name: "KJ-600",
    flag: "🇨🇳",
    role: "Carrier‑Based AEW&C",
    firstFlight: "2020",
    manufacturer: "Xi'an Aircraft",
    funFact: "China's answer to the E‑2 Hawkeye, designed for the new generation aircraft carriers.",
  },
  Ka27: {
    name: "Kamov Ka-27",
    flag: "🇷🇺",
    role: "Anti‑Submarine Helicopter",
    firstFlight: "1973",
    manufacturer: "Kamov",
    funFact: "Coaxial rotor design eliminates tail rotor; can operate in harsh weather from ships.",
  },
  Ka52: {
    name: "Kamov Ka-52 Alligator",
    flag: "🇷🇺",
    role: "Attack Helicopter",
    firstFlight: "1997",
    manufacturer: "Kamov",
    funFact: "Unique coaxial rotor design; features ejection seats for both pilots.",
  },
  MQ9: {
    name: "General Atomics MQ-9 Reaper",
    flag: "🇺🇸",
    role: "UCAV",
    firstFlight: "2001",
    manufacturer: "General Atomics",
    funFact: "Can loiter for 14+ hours while carrying Hellfire missiles and smart bombs.",
  },
  Mi24: {
    name: "Mil Mi-24 Hind",
    flag: "🇷🇺",
    role: "Attack / Transport Helicopter",
    firstFlight: "1969",
    manufacturer: "Mil",
    funFact: "Unique dual‑role gunship that can also carry 8 troops; nicknamed 'Flying Tank'.",
  },
  Mi28: {
    name: "Mil Mi-28 Havoc",
    flag: "🇷🇺",
    role: "Attack Helicopter",
    firstFlight: "1982",
    manufacturer: "Mil",
    funFact: "Russia's dedicated attack helicopter; designed to destroy tanks day and night.",
  },
  Mig29: {
    name: "Mikoyan MiG-29 Fulcrum",
    flag: "🇷🇺",
    role: "Multirole Fighter",
    firstFlight: "1977",
    manufacturer: "Mikoyan",
    funFact: "Designed as a Soviet answer to the F-16 and F/A-18.",
  },
  Mig31: {
    name: "Mikoyan MiG-31 Foxhound",
    flag: "🇷🇺",
    role: "Interceptor",
    firstFlight: "1975",
    manufacturer: "Mikoyan",
    funFact: "World's fastest operational combat aircraft; can reach Mach 2.83.",
  },
  Mirage2000: {
    name: "Dassault Mirage 2000",
    flag: "🇫🇷",
    role: "Multirole Fighter",
    firstFlight: "1978",
    manufacturer: "Dassault",
    funFact: "Fourth‑generation delta wing fighter exported to 9 countries.",
  },
  P3: {
    name: "Lockheed P-3 Orion",
    flag: "🇺🇸",
    role: "Maritime Patrol / ASW",
    firstFlight: "1959",
    manufacturer: "Lockheed",
    funFact: "Based on the Lockheed L-188 Electra; still in service after 60 years.",
  },
  RQ4: {
    name: "Northrop Grumman RQ-4 Global Hawk",
    flag: "🇺🇸",
    role: "High‑Altitude Surveillance UAV",
    firstFlight: "1998",
    manufacturer: "Northrop Grumman",
    funFact: "Can survey 100,000 sq km of terrain per day from 60,000 ft altitude.",
  },
  Rafale: {
    name: "Dassault Rafale",
    flag: "🇫🇷",
    role: "Multirole Fighter",
    firstFlight: "1986",
    manufacturer: "Dassault",
    funFact: "Can carry out air supremacy, interdiction, reconnaissance, and nuclear strike missions.",
  },
  SR71: {
    name: "Lockheed SR-71 Blackbird",
    flag: "🇺🇸",
    role: "Strategic Reconnaissance",
    firstFlight: "1964",
    manufacturer: "Lockheed",
    funFact: "Fastest air‑breathing manned aircraft; could outrun missiles with ease.",
  },
  Su24: {
    name: "Sukhoi Su-24 Fencer",
    flag: "🇷🇺",
    role: "Strike / Attack",
    firstFlight: "1967",
    manufacturer: "Sukhoi",
    funFact: "Variable‑sweep wing bomber; used extensively by Russia and former Soviet states.",
  },
  Su25: {
    name: "Sukhoi Su-25 Frogfoot",
    flag: "🇷🇺",
    role: "Close Air Support",
    firstFlight: "1975",
    manufacturer: "Sukhoi",
    funFact: "Russian equivalent of the A-10; heavily armored and designed for survivability.",
  },
  Su34: {
    name: "Sukhoi Su-34 Fullback",
    flag: "🇷🇺",
    role: "Strike Fighter",
    firstFlight: "1990",
    manufacturer: "Sukhoi",
    funFact: "Crew sit side‑by‑side; features a rest compartment for long missions.",
  },
  Su57: {
    name: "Sukhoi Su-57 Felon",
    flag: "🇷🇺",
    role: "5th‑Generation Stealth Fighter",
    firstFlight: "2010",
    manufacturer: "Sukhoi",
    funFact: "Russia's answer to the F-22; features stealth shaping and supercruise capability.",
  },
  "T-129 ATAK": {
    name: "TAI / AgustaWestland T129 ATAK",
    flag: "🇹🇷",
    role: "Attack Helicopter",
    firstFlight: "2009",
    manufacturer: "TAI / Leonardo",
    funFact: "Based on the A129 Mangusta; heavily modified with Turkish avionics and weapons.",
  },
  TB001: {
    name: "Baykar Bayraktar TB001",
    flag: "🇹🇷",
    role: "MALE UAV",
    firstFlight: "2019",
    manufacturer: "Baykar",
    funFact: "Twin‑engine drone with increased payload and endurance; also known as 'Akıncı B'.",
  },
  TB2: {
    name: "Bayraktar TB2",
    flag: "🇹🇷",
    role: "Tactical UAV",
    firstFlight: "2014",
    manufacturer: "Baykar",
    funFact: "Changed modern warfare; proved decisive in multiple conflicts including Nagorno‑Karabakh.",
  },
  Tornado: {
    name: "Panavia Tornado",
    flag: "🇬🇧🇩🇪🇮🇹",
    role: "Multirole Combat Aircraft",
    firstFlight: "1974",
    manufacturer: "Panavia Aircraft",
    funFact: "Developed by a tri‑national consortium (UK, Germany, Italy); features variable‑sweep wings.",
  },
  Tu160: {
    name: "Tupolev Tu-160 Blackjack",
    flag: "🇷🇺",
    role: "Strategic Bomber",
    firstFlight: "1981",
    manufacturer: "Tupolev",
    funFact: "Largest and heaviest combat aircraft ever built, nicknamed 'White Swan' by Russian crews.",
  },
  Tu22M: {
    name: "Tupolev Tu-22M Backfire",
    flag: "🇷🇺",
    role: "Strategic Bomber",
    firstFlight: "1969",
    manufacturer: "Tupolev",
    funFact: "Variable‑sweep supersonic bomber; used for maritime strike and land attack.",
  },
  Tu95: {
    name: "Tupolev Tu-95 Bear",
    flag: "🇷🇺",
    role: "Strategic Bomber / Missile Carrier",
    firstFlight: "1952",
    manufacturer: "Tupolev",
    funFact: "Only propeller‑driven strategic bomber still in use; extremely loud contra‑rotating props.",
  },
  U2: {
    name: "Lockheed U-2 Dragon Lady",
    flag: "🇺🇸",
    role: "High‑Altitude Reconnaissance",
    firstFlight: "1955",
    manufacturer: "Lockheed",
    funFact: "Operates at 70,000 ft; pilots wear full pressure suits similar to astronauts.",
  },
  UH60: {
    name: "Sikorsky UH-60 Black Hawk",
    flag: "🇺🇸",
    role: "Utility Helicopter",
    firstFlight: "1974",
    manufacturer: "Sikorsky",
    funFact: "Over 4,000 produced; backbone of US Army aviation for 40+ years.",
  },
  US2: {
    name: "ShinMaywa US‑2",
    flag: "🇯🇵",
    role: "Amphibious SAR",
    firstFlight: "2003",
    manufacturer: "ShinMaywa",
    funFact: "STOL amphibian with boundary layer control; can land in rough seas.",
  },
  V22: {
    name: "Bell Boeing V-22 Osprey",
    flag: "🇺🇸",
    role: "Tiltrotor VTOL",
    firstFlight: "1989",
    manufacturer: "Bell Boeing",
    funFact: "Combines helicopter hover with airplane speed and range; used by USMC, Navy, Air Force.",
  },
  Vulcan: {
    name: "Avro Vulcan",
    flag: "🇬🇧",
    role: "Strategic Bomber",
    firstFlight: "1952",
    manufacturer: "Avro",
    funFact: "Delta‑winged V‑bomber; famously operated in the Black Buck raids during the Falklands War.",
  },
  WZ7: {
    name: "WZ‑7 Soaring Dragon",
    flag: "🇨🇳",
    role: "High‑Altitude Surveillance UAV",
    firstFlight: "2010",
    manufacturer: "AVIC",
    funFact: "Chinese equivalent of the Global Hawk; designed for long‑range reconnaissance.",
  },
  XB70: {
    name: "North American XB‑70 Valkyrie",
    flag: "🇺🇸",
    role: "Supersonic Bomber Prototype",
    firstFlight: "1964",
    manufacturer: "North American Aviation",
    funFact: "Mach 3 bomber prototype; only two built, one destroyed in a mid‑air collision.",
  },
  Y20: {
    name: "Xi'an Y‑20 Kunpeng",
    flag: "🇨🇳",
    role: "Strategic Airlifter",
    firstFlight: "2013",
    manufacturer: "Xi'an Aircraft",
    funFact: "China's first indigenously developed heavy transport; comparable to the C‑17.",
  },
  YF23: {
    name: "Northrop YF‑23 Black Widow II",
    flag: "🇺🇸",
    role: "Stealth Fighter Prototype",
    firstFlight: "1990",
    manufacturer: "Northrop / McDonnell Douglas",
    funFact: "Lost to the YF‑22 in the ATF competition; considered stealthier and faster.",
  },
  Z19: {
    name: "Harbin Z‑19",
    flag: "🇨🇳",
    role: "Reconnaissance / Attack Helicopter",
    firstFlight: "2010",
    manufacturer: "Harbin Aircraft",
    funFact: "Light attack helicopter with tandem cockpit; used by Chinese Army Aviation.",
  },
};

/**
 * Look up aircraft info by the exact prediction name (key in this database).
 */
export function getAircraftInfo(predictionName: string): AircraftInfo | null {
  return aircraftDatabase[predictionName] || null;
}

export default aircraftDatabase;